---
- name: Import role to install Docker
  import_role:
    name: docker_role

- name: Log into DockerHub
  docker_login:
    username: dimitrii89
    password: vdk69346934

- name: Pull an image with web-app
  docker_image:
    name: dimitrii89/exam-images:web-app-latest

- name: Run 3 docker containers with web-app on different ports
  docker_container:
    name: "web-app-{{ item.num }}"
    image: dimitrii89/exam-images:web-app-latest
    networks:
      - name: my-network
    state: started
    ports:
      - "{{ item.port }}:5000"
  loop:
    - { num: '1', port: '2000' }
    - { num: '2', port: '3000' }
    - { num: '3', port: '4000' }

# tasks file for roles/web_app_role
